appiumtest:
	mvn archetype:generate -DgroupId=com.streambox.appiumtest -DartifactId=appiumtest -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
clean:
	rm -rf appiumtest/target
